In [ ]:
import nltk
# natural language tool kit


nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

True

In [16]:
paragraph='He is a good boy. She is a good girl. boy and girl are good.'

#tekenization=berak into part 
#sentance tokenization = breaking into sentance     

sentance=nltk.sent_tokenize(paragraph)
print(sentance)

#word tokennization =break into words

word=nltk.word_tokenize(paragraph)
print(word)

['He is a good boy.', 'She is a good girl.', 'boy and girl are good.']
['He', 'is', 'a', 'good', 'boy', '.', 'She', 'is', 'a', 'good', 'girl', '.', 'boy', 'and', 'girl', 'are', 'good', '.']

In [195]:
from nltk.corpus import stopwords
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [7]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()
words=['playng','where','plays','goods']

for word in words:
    print(ps.stem(word))

playng
where
play
good

In [9]:
import cv2
import cv2

print(cv2.data.haarcascades)

C:\Users\vilas\AppData\Roaming\Python\Python313\site-packages\cv2\data\

In [39]:
import pandas as pd
df=pd.DataFrame({
    'in':['He is a goods boy playing.','She is a good girls.','boys & girl are good.'],
    'op':['P','P','N']
})
df

                           in op
0  He is a goods boy playing.  P
1        She is a good girls.  P
2       boys & girl are good.  N

In [66]:
# cleaning
# removo punctuvation (omy dot removo) 
# romove stopwords 
# r
#stemming /lematization

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
wl=WordNetLemmatizer
ps=PorterStemmer()
corpus=[]
import re
for i in range(len(df)):
    rp=re.sub('[^a-zA-Z]'," ",df["in"][i])
    rp=rp.lower()
    rp=rp.split()

    rp=[ps.stem(word) for word in rp if not word in stopwords.words('english')]
    rp=" ".join(rp)
    print(rp)
    corpus.append(rp)
df=pd.DataFrame({'in':corpus})
print(df)

good boy play
good girl
boy girl good
              in
0  good boy play
1      good girl
2  boy girl good

In [84]:
import pandas as pd
df=pd.DataFrame({
    'in':['He is a goods boy playing.','She is a good girls.','boys & girl are good.'],
    'op':['P','P','N']
})
df

                           in op
0  He is a goods boy playing.  P
1        She is a good girls.  P
2       boys & girl are good.  N

In [116]:
import re
l=[]
for i in range(len(df)):
    r=re.sub('[^a-zA-Z]'," ",df['in'][i])
    
    r=r.lower()
    r=r.split()
    r=[ps.stem(word) for word in r if not word in stopwords.words('english')]
    r=" ".join(r)
    print(r)
    l.append(r)
pd.DataFrame({'in':l})


from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

X=cv.fit_transform(df['in']).toarray(),columns=cv.get_feature_names_out()

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2696438752.py, line 18)

In [120]:
#count vectorize 

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

X=cv.fit_transform(corpus)
print(X.toarray())
#pd.DataFrame(cv.fit_transform(df['in']).toarray(),columns=cv.get_feature_names_out())

df=pd.DataFrame(
    x.toarray(),
    columns=cv.get_feature_names_out()
)
df

[[0 0 0 1 0 1]
 [1 1 0 0 0 1]
 [0 0 1 1 1 0]]

   easy  is  learning  love  machine  python
0     0   0         0     1        0       1
1     1   1         0     0        0       1
2     0   0         1     1        1       0

In [83]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
corpus = [
    "I love Python",
    "Python is easy",
    "I love machine learning"
]

x=cv.fit_transform(corpus)
print(cv.get_feature_names_out())
x.toarray()
df=pd.DataFrame(
    x.toarray(),
    columns=cv.get_feature_names_out()
)
df

['easy' 'is' 'learning' 'love' 'machine' 'python']

   easy  is  learning  love  machine  python
0     0   0         0     1        0       1
1     1   1         0     0        0       1
2     0   0         1     1        1       0

✅ Lowercase conversion

✅ Remove punctuation

✅ Tokenization

✅ Remove stopwords

✅ Stemming

✅ Lemmatizatio

In [ ]:
sentences = [
    "I am learning Machine Learning!!!",
    "The cats are playing in the garden.",
    "He studies Python, Java, and C++.",
    "This movie is really amazing!!!",
    "Running is better than sitting all day.",
    "Children were eating delicious chocolates.",
    "I don't like waiting for buses.",
    "Artificial Intelligence is changing the world.",
    "She has completed her assignments successfully.",
    "Natural Language Processing is very interesting."
]
print(sentences)

['I am learning Machine Learning!!!', 'The cats are playing in the garden.', 'He studies Python, Java, and C++.', 'This movie is really amazing!!!', 'Running is better than sitting all day.', 'Children were eating delicious chocolates.', "I don't like waiting for buses.", 'Artificial Intelligence is changing the world.', 'She has completed her assignments successfully.', 'Natural Language Processing is very interesting.']

In [127]:
import nltk
import string
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vilas\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vilas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\vilas\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()
stop_words=set(stopwords.words('english'))

In [ ]:
#complate nlp processing
import pandas as pd
import numpy as np
import re
for sentence in sentences:
     #lowercase
    sentence=sentence.lower()
    ##sentence=re.sub('[^a-zA-Z]'," ",sentence)
    sentence = re.sub(r'[^\w\s]', '', sentence)

    # tokenizetion
    words=word_tokenize(sentence)

    #remove stopword
    words=[word for word in words if word not in stop_words]

    #steamimg
    stem_words=[ps.stem(word) for word in words]
    

    #lemmatization 
    lemma_words=[lemmatizer.lemmatize(word) for word in words]
    print("Original :", sentence)
    print("Tokens   :", words)
    print("Stem     :", stem_words)
    print("Lemma    :", lemma_words)
    print("*" * 50)

Original : i am learning machine learning
Tokens   : ['learning', 'machine', 'learning']
Stem     : ['learn', 'machin', 'learn']
Lemma    : ['learning', 'machine', 'learning']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K
Original : the cats are playing in the garden
Tokens   : ['cats', 'playing', 'garden']
Stem     : ['cat', 'play', 'garden']
Lemma    : ['cat', 'playing', 'garden']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K
Original : he studies python java and c
Tokens   : ['studies', 'python', 'java', 'c']
Stem     : ['studi', 'python', 'java', 'c']
Lemma    : ['study', 'python', 'java', 'c']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K
Original : this movie is really amazing
Tokens   : ['movie', 'really', 'amazing']
Stem     : ['movi', 'realli', 'amaz']
Lemma    : ['movie', 'really', 'amazing']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K
Original : running is better than sitting all day
Tokens   : ['running', 'better', 'sitting', 'day']
Stem     : ['run', 'better', 'sit', 'day']
Lemma    : ['running', 'better', 'sitting', 'day']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K
Original : children were eating delicious chocolates
Tokens   : ['children', 'eating', 'delicious', 'chocolates']
Stem     : ['children', 'eat', 'delici', 'chocol']
Lemma    : ['child', 'eating', 'delicious', 'chocolate']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K
Original : i dont like waiting for buses
Tokens   : ['dont', 'like', 'waiting', 'buses']
Stem     : ['dont', 'like', 'wait', 'buse']
Lemma    : ['dont', 'like', 'waiting', 'bus']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K
Original : artificial intelligence is changing the world
Tokens   : ['artificial', 'intelligence', 'changing', 'world']
Stem     : ['artifici', 'intellig', 'chang', 'world']
Lemma    : ['artificial', 'intelligence', 'changing', 'world']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K
Original : she has completed her assignments successfully
Tokens   : ['completed', 'assignments', 'successfully']
Stem     : ['complet', 'assign', 'success']
Lemma    : ['completed', 'assignment', 'successfully']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K
Original : natural language processing is very interesting
Tokens   : ['natural', 'language', 'processing', 'interesting']
Stem     : ['natur', 'languag', 'process', 'interest']
Lemma    : ['natural', 'language', 'processing', 'interesting']
**************************************************
@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K@K

In [ ]:
import re #regular expression 
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer


stop_words=set(stopwords.words('english'))
ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()

In [167]:
text_data = [
    "I LOVE Python!!!",
    "Machine Learning is AMAZING.",
    "Call me at 9876543210.",
    "Visit https://google.com now.",
    "My email is abc@gmail.com.",
    "<h1>Hello World</h1>",
    "Python version 3.13 released.",
    "Data Science is fun 😊",
    "Natural Language Processing (NLP) is awesome!!",
    "Artificial Intelligence is changing the world.",
    "Running, playing, studying and reading books.",
    "Children are eating chocolates.",
    "The cats were running in the garden.",
    "Don't forget to complete your assignments.",
    "Today's weather is very pleasant."
]

In [190]:
r=[]
for sentence in text_data:
    original=sentence
    #print(original)
    #1 lowercase
    sentence=sentence.lower()

    #2 remove html tags
    sentence=re.sub(r'<.*?>',' ',sentence)

    #3 remove url
    sentence = re.sub(r'https?://\S+', '', sentence)

    #4 removal email
    sentence = re.sub(r'\S+@\S+', '', sentence)
    #5 removo numbers
    sentence=re.sub(r'\d+','',sentence)

    #6 removo punctuvation
    sentence=sentence.translate(str.maketrans('','',string.punctuation)) # replace,replace with ,delete

    # removo extra space
    sentence = re.sub(r'\s+', ' ', sentence).strip()

    #8 tokenization
    words=word_tokenize(sentence)

    #9 removo stopwords
    words=[word for word in words if word not in stop_words]

    #10 stemmimg
    stem_words=[ps.stem(word) for word in words]

    #11 lemmatization 
    lemma_words=[lemmatizer.lemmatize(word) for word in words]

    r.append({
        'orignal':original,
        'tokens':words,
        'stemmed': stem_words,
        'Lemmatized':lemma_words,
        
    })

df=pd.DataFrame(r)

df

,orignal,tokens,stemmed,Lemmatized
0,I LOVE Python!!!,"[love, python]","[love, python]","[love, python]"
1,Machine Learning is AMAZING.,"[machine, learning, amazing]","[machin, learn, amaz]","[machine, learning, amazing]"
2,Call me at 9876543210.,[call],[call],[call]
3,Visit https://google.com now.,[visit],[visit],[visit]
4,My email is abc@gmail.com.,[email],[email],[email]
5,<h1>Hello World</h1>,"[hello, world]","[hello, world]","[hello, world]"
6,Python version 3.13 released.,"[python, version, released]","[python, version, releas]","[python, version, released]"
7,Data Science is fun 😊,"[data, science, fun, 😊]","[data, scienc, fun, 😊]","[data, science, fun, 😊]"
8,Natural Language Processing (NLP) is awesome!!,"[natural, language, processing, nlp, awesome]","[natur, languag, process, nlp, awesom]","[natural, language, processing, nlp, awesome]"
9,Artificial Intelligence is changing the world.,"[artificial, intelligence, changing, world]","[artifici, intellig, chang, world]","[artificial, intelligence, changing, world]"
10,"Running, playing, studying and reading books.","[running, playing, studying, reading, books]","[run, play, studi, read, book]","[running, playing, studying, reading, book]"
11,Children are eating chocolates.,"[children, eating, chocolates]","[children, eat, chocol]","[child, eating, chocolate]"
12,The cats were running in the garden.,"[cats, running, garden]","[cat, run, garden]","[cat, running, garden]"
13,Don't forget to complete your assignments.,"[dont, forget, complete, assignments]","[dont, forget, complet, assign]","[dont, forget, complete, assignment]"
14,Today's weather is very pleasant.,"[todays, weather, pleasant]","[today, weather, pleasant]","[today, weather, pleasant]"

In [192]:
text_data=[
    "The government announced new education policies today.",
    "Stock markets reached an all-time high this week.",
    "Scientists developed a new AI-powered healthcare system.",
    "Heavy rainfall affected transportation across the city.",
    "Researchers discovered a new species in the Amazon rainforest.",
    "The cricket team won the championship after a thrilling final.",
    "Electric vehicles are becoming increasingly popular worldwide.",
    "New cybersecurity threats have emerged this year.",
    "Universities are introducing more AI-related courses.",
    "Space agencies plan another mission to the Moon."
]

In [193]:
r=[]
for sentence in text_data:
    original=sentence
    #print(original)
    #1 lowercase
    sentence=sentence.lower()

    #2 remove html tags
    sentence=re.sub(r'<.*?>',' ',sentence)

    #3 remove url
    sentence = re.sub(r'https?://\S+', '', sentence)

    #4 removal email
    sentence = re.sub(r'\S+@\S+', '', sentence)
    #5 removo numbers
    sentence=re.sub(r'\d+','',sentence)

    #6 removo punctuvation
    sentence=sentence.translate(str.maketrans('','',string.punctuation)) # replace,replace with ,delete

    # removo extra space
    sentence = re.sub(r'\s+', ' ', sentence).strip()

    #8 tokenization
    words=word_tokenize(sentence)

    #9 removo stopwords
    words=[word for word in words if word not in stop_words]

    #10 stemmimg
    stem_words=[ps.stem(word) for word in words]

    #11 lemmatization 
    lemma_words=[lemmatizer.lemmatize(word) for word in words]

    r.append({
        'orignal':original,
        'tokens':words,
        'stemmed': stem_words,
        'Lemmatized':lemma_words,
        
    })

df=pd.DataFrame(r)

df

,orignal,tokens,stemmed,Lemmatized
0,The government announced new education policie...,"[government, announced, new, education, polici...","[govern, announc, new, educ, polici, today]","[government, announced, new, education, policy..."
1,Stock markets reached an all-time high this week.,"[stock, markets, reached, alltime, high, week]","[stock, market, reach, alltim, high, week]","[stock, market, reached, alltime, high, week]"
2,Scientists developed a new AI-powered healthca...,"[scientists, developed, new, aipowered, health...","[scientist, develop, new, aipow, healthcar, sy...","[scientist, developed, new, aipowered, healthc..."
3,Heavy rainfall affected transportation across ...,"[heavy, rainfall, affected, transportation, ac...","[heavi, rainfal, affect, transport, across, citi]","[heavy, rainfall, affected, transportation, ac..."
4,Researchers discovered a new species in the Am...,"[researchers, discovered, new, species, amazon...","[research, discov, new, speci, amazon, rainfor...","[researcher, discovered, new, specie, amazon, ..."
5,The cricket team won the championship after a ...,"[cricket, team, championship, thrilling, final]","[cricket, team, championship, thrill, final]","[cricket, team, championship, thrilling, final]"
6,Electric vehicles are becoming increasingly po...,"[electric, vehicles, becoming, increasingly, p...","[electr, vehicl, becom, increasingli, popular,...","[electric, vehicle, becoming, increasingly, po..."
7,New cybersecurity threats have emerged this year.,"[new, cybersecurity, threats, emerged, year]","[new, cybersecur, threat, emerg, year]","[new, cybersecurity, threat, emerged, year]"
8,Universities are introducing more AI-related c...,"[universities, introducing, airelated, courses]","[univers, introduc, airel, cours]","[university, introducing, airelated, course]"
9,Space agencies plan another mission to the Moon.,"[space, agencies, plan, another, mission, moon]","[space, agenc, plan, anoth, mission, moon]","[space, agency, plan, another, mission, moon]"

In [1]:
# revised_project
import pandas as pd 


df=pd.read_csv(r"C:\Users\vilas\Downloads\archive (1)\spam (or) ham.csv")
df

df['Class'].unique()
df['Class'].value_counts()
df.shape
df.isnull().sum()
df.duplicated().sum()

df

     Class                                                sms
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name
5572  spam  This is the 2nd time we have tried 2 contact u...

[5573 rows x 2 columns]

In [8]:
df.isnull().sum()
df.value_counts()

Class  sms
ham    Sorry, I'll call later                                                                                                                                                                                                                   30
       I cant pick the phone right now. Pls send a message                                                                                                                                                                                      12
       Ok...                                                                                                                                                                                                                                    10
       Okie                                                                                                                                                                                                                                      4
       Ok.                                                                                                                                                                                                                                       4
                                                                                                                                                                                                                                                ..
       I was about to do it when i texted. I finished a long time ago and showered and er'ything!                                                                                                                                                1
       I wanted to wish you a Happy New Year and I wanted to talk to you about some legal advice to do with when Gary and I split but in person. I'll make a trip to Ptbo for that. I hope everything is good with you babe and I love ya :)     1
       I wanted to ask ü to wait 4 me to finish lect. Cos my lect finishes in an hour anyway.                                                                                                                                                    1
       I want to tell you how bad I feel that basically the only times I text you lately are when I need drugs                                                                                                                                   1
spam   we tried to contact you re your response to our offer of a new nokia fone and camcorder hit reply or call 08000930705 for delivery                                                                                                        1
Name: count, Length: 5170, dtype: int64

In [ ]:
#text preprocessing 
r=[]
import re
import nltk
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
ps=PorterStemmer()
from nltk.corpus import  stopwords

In [34]:
corpus=[]
for i in range(len(df)):
    r=re.sub('[^a-zA-Z]'," ",df['sms'][i]) #sub=substitude
    #re.sub(pattern,replacement,string)
    r=r.lower()
    r=r.split()
     
    r=[ps.stem(word) for word in r if not word in stopwords.words('english')]
    #return to string from list
    r=" ".join(r)
    corpus.append(r)

In [40]:
df

     Class                                                sms
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name
5572  spam  This is the 2nd time we have tried 2 contact u...

[5573 rows x 2 columns]

In [46]:
# count tokenization (for structure data)
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus).toarray()
X.shape
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5573, 6296))

In [48]:
#label encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Class']=le.fit_transform(df[['Class']])
y=df['Class']

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.8,random_state=True)

from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb.fit(X_train,y_train)
y_predtest=nb.predict(X_test)
y_predtrain=nb.predict(X_train)


from sklearn.metrics import accuracy_score

acctest=accuracy_score(y_test,y_predtest)
acctrain=accuracy_score(y_train,y_predtrain)

print('acctest:',acctest)
print('acctrain:',acctrain)

acctest: 0.9755550571877103
acctrain: 0.9937163375224417

In [79]:
# prediction
new_mail='This is a reminder that our project meeting is scheduled for tomorrow at 10:00 AM in the conference room. Please bring the latest progress report.Thank you.'


 

corpus=[]
r=re.sub("[^a-zA-Z]"," ",new_mail)
r=r.lower()
r=r.split()
#r=[ps.stem(word) for word in r if not word in stopwords.words('english') ]
r=[ps.stem(word) for word in r if not word in set(stopwords.words('english'))]

r=" ".join(r)
corpus.append(r)
print(corpus)

X=cv.transform(corpus).toarray()
X.shape

['remind project meet schedul tomorrow confer room pleas bring latest progress report thank']

(1, 13)

In [77]:
pred=nb.predict(X)

ValueError: X has 13 features, but MultinomialNB is expecting 6296 features as input.